# Generated by Django 5.2.6 on 2025-09-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_posts", to="posts.tag"
            ),
        ),
    ]
