# Generated by Django 5.2.6 on 2025-09-24 17:55

from django.db import migrations
from django.conf import settings

def create_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model("profiles", "Profile")
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]